<?php

/**
 * Implements hook_menu().
 * @link http://api.drupal.org/api/function/hook_menu/7
 */
function url_keyword_menu() {
  $items = array();
  $items['admin/door3/url_keyword'] = array(
    'title' => 'URL Keyword',
    'description' => 'Configure URL Keyword.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('url_keyword_admin_form'),
    'access arguments' => array('administer site configuration'),
    'menu name' => 'management',
    'file' => 'url_keyword.admin.inc',
  );
  $items['admin/door3/url_keyword/create'] = array(
    'title' => 'Create Keyword',
    'description' => 'Create Keyword.',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('url_keyword_create_form'),
    'access arguments' => array('administer site configuration'),
    'menu name' => 'management',
    'file' => 'url_keyword.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_preprocess_page().
 */

function url_keyword_preprocess_page(&$vars) {
  if ($vars['node']->type == 'ppc') {
      $actual_link = "$_SERVER[REQUEST_URI]";
      $indexOf = strrpos($actual_link, "kw=");

    if ($indexOf > 1) {
      list($leftover, $kw) = split('kw=', $actual_link);
      list($kw, $leftover) = split('&', $kw);
      $query = db_select('url_keyword', 'uk');
      $query->fields('uk', array('kwid','keyword','page_title','h1'))
            ->condition('uk.keyword', $kw, '=');
      $results = $query->execute();

      if ($results) {
        foreach($results as $result) {
          $row[] = array(
          'kwid' => $result->kwid,
          'keyword' => $result->keyword,
          'page_title' => $result->page_title,
          'h1' => $result->h1,
          );
        }
      }
    }
  }
}

